// České názvy měst, metropolitní oblasti a turistické regiony.
// Klíče CITY_CS odpovídají názvům měst v data/airports.json (OpenFlights).

export const CITY_CS = {
  Vienna: 'Vídeň', Prague: 'Praha', Munich: 'Mnichov', Nuremberg: 'Norimberk', Dresden: 'Drážďany',
  Leipzig: 'Lipsko', Berlin: 'Berlín', Hamburg: 'Hamburk', Cologne: 'Kolín nad Rýnem', Bremen: 'Brémy',
  Basel: 'Basilej', Zurich: 'Curych', Geneva: 'Ženeva', Salzburg: 'Salcburk', Linz: 'Linec',
  Graz: 'Štýrský Hradec', Klagenfurt: 'Klagenfurt', Kosice: 'Košice', Budapest: 'Budapešť',
  Krakow: 'Krakov', Katowice: 'Katovice', Wroclaw: 'Vratislav', Warsaw: 'Varšava', Gdansk: 'Gdaňsk',
  Poznan: 'Poznaň', Lodz: 'Lodž', London: 'Londýn', Paris: 'Paříž', Rome: 'Řím', Milan: 'Milán',
  Venice: 'Benátky', Naples: 'Neapol', Florence: 'Florencie', Bologna: 'Boloňa', Turin: 'Turín',
  Genoa: 'Janov', Trieste: 'Terst', Seville: 'Sevilla', Valencia: 'Valencie', Lisbon: 'Lisabon',
  Athens: 'Atény', Thessaloniki: 'Soluň', Heraklion: 'Heraklion (Kréta)', Chania: 'Chania (Kréta)',
  Corfu: 'Korfu', Kerkyra: 'Korfu', Larnaca: 'Larnaka', Paphos: 'Pafos', Zagreb: 'Záhřeb',
  Ljubljana: 'Lublaň', Belgrade: 'Bělehrad', Bucharest: 'Bukurešť', 'Cluj-napoca': 'Kluž',
  Brussels: 'Brusel', Copenhagen: 'Kodaň', Kiev: 'Kyjev', Lviv: 'Lvov', Chisinau: 'Kišiněv',
  Marrakech: 'Marrákeš', Tangier: 'Tanger', Cairo: 'Káhira', Amman: 'Ammán', Dubai: 'Dubaj',
  Muscat: 'Maskat', Singapore: 'Singapur', Tokyo: 'Tokio', Seoul: 'Soul', Beijing: 'Peking',
  Shanghai: 'Šanghaj', 'Hong Kong': 'Hongkong', Delhi: 'Dillí', 'New Delhi': 'Dillí', Mumbai: 'Bombaj',
  'Ho Chi Minh City': 'Ho Či Minovo Město', 'Mexico City': 'Ciudad de México', 'Cape Town': 'Kapské Město',
  Mallorca: 'Mallorca', 'Palma de Mallorca': 'Palma de Mallorca', Gerona: 'Girona', Tenerife: 'Tenerife',
  'Gran Canaria': 'Gran Canaria', Arrecife: 'Lanzarote', Funchal: 'Madeira', Malta: 'Malta',
  Copenhague: 'Kodaň', Oporto: 'Porto', Strasbourg: 'Štrasburk', Lyon: 'Lyon', Nice: 'Nice',
  Marseille: 'Marseille', Bordeaux: 'Bordeaux', Toulouse: 'Toulouse', Antwerp: 'Antverpy',
  Gothenburg: 'Göteborg', 'St. Petersburg': 'Petrohrad', Moscow: 'Moskva', Istanbul: 'Istanbul',
  Jerusalem: 'Jeruzalém', 'Tel-aviv': 'Tel Aviv', Havana: 'Havana', Washington: 'Washington',
  Edinburgh: 'Edinburgh', Reykjavik: 'Reykjavík', Riga: 'Riga', Tallinn: 'Tallinn', Vilnius: 'Vilnius',
  Sofia: 'Sofie', Tirana: 'Tirana', Podgorica: 'Podgorica', Skopje: 'Skopje', Sarajevo: 'Sarajevo',
  Bari: 'Bari', Palermo: 'Palermo', Catania: 'Catania', Cagliari: 'Cagliari', Pisa: 'Pisa',
  Bergamo: 'Bergamo', Treviso: 'Treviso', Beauvais: 'Beauvais', Charleroi: 'Charleroi',
};

// Český název města/destinace podle IATA kódu letiště (má přednost před CITY_CS).
export const AIRPORT_CITY_CS = {
  PRG: 'Praha', BRQ: 'Brno', OSR: 'Ostrava', PED: 'Pardubice', KLV: 'Karlovy Vary', BTS: 'Bratislava',
  KSC: 'Košice', TAT: 'Poprad', VIE: 'Vídeň', LNZ: 'Linec', GRZ: 'Štýrský Hradec', SZG: 'Salcburk',
  INN: 'Innsbruck', KLU: 'Klagenfurt', BER: 'Berlín', MUC: 'Mnichov', NUE: 'Norimberk', DRS: 'Drážďany',
  LEJ: 'Lipsko', FRA: 'Frankfurt', HHN: 'Frankfurt-Hahn', HAM: 'Hamburk', CGN: 'Kolín nad Rýnem', DUS: 'Düsseldorf',
  NRN: 'Weeze', DTM: 'Dortmund', STR: 'Stuttgart', FMM: 'Memmingen (Mnichov)', HAJ: 'Hannover', BRE: 'Brémy',
  FKB: 'Karlsruhe/Baden-Baden', FDH: 'Friedrichshafen', PAD: 'Paderborn', LBC: 'Lübeck', SCN: 'Saarbrücken', ERF: 'Erfurt',
  WAW: 'Varšava', WMI: 'Varšava-Modlin', KRK: 'Krakov', KTW: 'Katovice', WRO: 'Vratislav', GDN: 'Gdaňsk',
  POZ: 'Poznaň', LCJ: 'Lodž', RZE: 'Řešov', SZZ: 'Štětín', LUZ: 'Lublin', BZG: 'Bydhošť',
  IEG: 'Zelená Hora', BUD: 'Budapešť', DEB: 'Debrecín', ZRH: 'Curych', GVA: 'Ženeva', BSL: 'Basilej',
  BRN: 'Bern', FCO: 'Řím', CIA: 'Řím-Ciampino', MXP: 'Milán', LIN: 'Milán-Linate', BGY: 'Milán-Bergamo',
  VCE: 'Benátky', TSF: 'Benátky-Treviso', NAP: 'Neapol', FLR: 'Florencie', PSA: 'Pisa', BLQ: 'Boloňa',
  TRN: 'Turín', GOA: 'Janov', TRS: 'Terst', VRN: 'Verona', BRI: 'Bari', BDS: 'Brindisi',
  PMO: 'Palermo', CTA: 'Catania', TPS: 'Trapani', CAG: 'Cagliari', OLB: 'Olbia', AHO: 'Alghero',
  PSR: 'Pescara', AOI: 'Ancona', CIY: 'Comiso', SUF: 'Lamezia Terme', REG: 'Reggio Calabria', RMI: 'Rimini',
  PEG: 'Perugia', CUF: 'Cuneo', BCN: 'Barcelona', GRO: 'Barcelona-Girona', REU: 'Barcelona-Reus', MAD: 'Madrid',
  SVQ: 'Sevilla', VLC: 'Valencie', AGP: 'Málaga', ALC: 'Alicante', PMI: 'Mallorca', IBZ: 'Ibiza',
  MAH: 'Menorca', TFS: 'Tenerife (jih)', TFN: 'Tenerife (sever)', LPA: 'Gran Canaria', ACE: 'Lanzarote', FUE: 'Fuerteventura',
  SPC: 'La Palma', BIO: 'Bilbao', SDR: 'Santander', SCQ: 'Santiago de Compostela', VGO: 'Vigo', OVD: 'Asturie',
  GRX: 'Granada', XRY: 'Jerez', RMU: 'Murcia', ZAZ: 'Zaragoza', LEI: 'Almería', VLL: 'Valladolid',
  LIS: 'Lisabon', OPO: 'Porto', FAO: 'Faro (Algarve)', FNC: 'Madeira', PDL: 'Azory (Ponta Delgada)', TER: 'Azory (Terceira)',
  CDG: 'Paříž', ORY: 'Paříž-Orly', BVA: 'Paříž-Beauvais', NCE: 'Nice', MRS: 'Marseille', LYS: 'Lyon',
  TLS: 'Toulouse', BOD: 'Bordeaux', NTE: 'Nantes', BES: 'Brest', CCF: 'Carcassonne', BZR: 'Béziers',
  FNI: 'Nîmes', PUF: 'Pau', LIL: 'Lille', SXB: 'Štrasburk', MPL: 'Montpellier', BIQ: 'Biarritz',
  AJA: 'Korsika (Ajaccio)', BIA: 'Korsika (Bastia)', PGF: 'Perpignan', LRH: 'La Rochelle', TUF: 'Tours', LIG: 'Limoges',
  EGC: 'Bergerac', RDZ: 'Rodez', DLE: 'Dole', MLH: 'Mylhúzy', EAP: 'Basilej-Mylhúzy', AMS: 'Amsterdam',
  EIN: 'Eindhoven', RTM: 'Rotterdam', MST: 'Maastricht', BRU: 'Brusel', CRL: 'Brusel-Charleroi', ANR: 'Antverpy',
  LGG: 'Lutych', LUX: 'Lucemburk', LHR: 'Londýn-Heathrow', LGW: 'Londýn-Gatwick', STN: 'Londýn-Stansted', LTN: 'Londýn-Luton',
  LCY: 'Londýn-City', SEN: 'Londýn-Southend', MAN: 'Manchester', LPL: 'Liverpool', BHX: 'Birmingham', BRS: 'Bristol',
  EDI: 'Edinburgh', GLA: 'Glasgow', PIK: 'Glasgow-Prestwick', BFS: 'Belfast', NCL: 'Newcastle', LBA: 'Leeds',
  EMA: 'East Midlands', ABZ: 'Aberdeen', DUB: 'Dublin', ORK: 'Cork', SNN: 'Shannon', NOC: 'Knock',
  KIR: 'Kerry', CPH: 'Kodaň', BLL: 'Billund', AAR: 'Aarhus', ARN: 'Stockholm', BMA: 'Stockholm-Bromma',
  NYO: 'Stockholm-Skavsta', VST: 'Stockholm-Västerås', GOT: 'Göteborg', MMX: 'Malmö', OSL: 'Oslo', TRF: 'Oslo-Torp',
  BGO: 'Bergen', TRD: 'Trondheim', SVG: 'Stavanger', HEL: 'Helsinky', TMP: 'Tampere', RVN: 'Rovaniemi (Laponsko)',
  KEF: 'Reykjavík', TOS: 'Tromsø', RIX: 'Riga', TLL: 'Tallinn', VNO: 'Vilnius', KUN: 'Kaunas',
  PLQ: 'Palanga', ZAG: 'Záhřeb', SPU: 'Split', DBV: 'Dubrovník', ZAD: 'Zadar', PUY: 'Pula',
  RJK: 'Rijeka', LJU: 'Lublaň', BEG: 'Bělehrad', INI: 'Niš', SJJ: 'Sarajevo', TZL: 'Tuzla',
  BNX: 'Banja Luka', TGD: 'Podgorica', TIV: 'Tivat', TIA: 'Tirana', SKP: 'Skopje', OHD: 'Ochrid',
  PRN: 'Priština', SOF: 'Sofie', VAR: 'Varna', BOJ: 'Burgas', PDV: 'Plovdiv', OTP: 'Bukurešť',
  BBU: 'Bukurešť-Băneasa', CLJ: 'Kluž', TSR: 'Temešvár', IAS: 'Jasy', SBZ: 'Sibiu', KIV: 'Kišiněv',
  ATH: 'Atény', SKG: 'Soluň', HER: 'Kréta (Heraklion)', CHQ: 'Kréta (Chania)', RHO: 'Rhodos', CFU: 'Korfu',
  KGS: 'Kos', ZTH: 'Zakynthos', JTR: 'Santorini', JMK: 'Mykonos', EFL: 'Kefalonie', PVK: 'Preveza (Lefkada)',
  KLX: 'Kalamata', SMI: 'Samos', MJT: 'Lesbos', JSI: 'Skiathos', LCA: 'Larnaka', PFO: 'Pafos',
  MLA: 'Malta', IST: 'Istanbul', SAW: 'Istanbul-Sabiha', AYT: 'Antalya', DLM: 'Dalaman', BJV: 'Bodrum',
  ADB: 'Izmir', ESB: 'Ankara', GZP: 'Alanya', TLV: 'Tel Aviv', AMM: 'Ammán', AQJ: 'Akaba',
  DXB: 'Dubaj', DWC: 'Dubaj-Al Maktoum', AUH: 'Abú Dhabí', SHJ: 'Šardžá', DOH: 'Dauhá', DIA: 'Dauhá', MCT: 'Maskat',
  BAH: 'Bahrajn', KWI: 'Kuvajt', RUH: 'Rijád', JED: 'Džidda', BEY: 'Bejrút', RKT: 'Ras al-Chajma',
  CAI: 'Káhira', HRG: 'Hurghada', SSH: 'Šarm aš-Šajch', RMF: 'Marsa Alam', RAK: 'Marrákeš', AGA: 'Agadir',
  FEZ: 'Fès', TNG: 'Tanger', CMN: 'Casablanca', RBA: 'Rabat', NDR: 'Nador', ESU: 'Essaouira',
  TUN: 'Tunis', NBE: 'Enfidha (Tunisko)', DJE: 'Džerba', MIR: 'Monastir', ALG: 'Alžír', CPT: 'Kapské Město',
  JNB: 'Johannesburg', NBO: 'Nairobi', MBA: 'Mombasa', ZNZ: 'Zanzibar', JRO: 'Kilimandžáro', DAR: 'Dar es Salaam',
  ADD: 'Addis Abeba', MRU: 'Mauricius', SEZ: 'Seychely', RUN: 'Réunion', SID: 'Kapverdy (Sal)', BVC: 'Kapverdy (Boa Vista)',
  WDH: 'Windhoek', VFA: 'Viktoriiny vodopády', LOS: 'Lagos', ACC: 'Akkra', DSS: 'Dakar', BKK: 'Bangkok',
  DMK: 'Bangkok-Don Mueang', HKT: 'Phuket', CNX: 'Čiang Mai', USM: 'Koh Samui', KBV: 'Krabi', DPS: 'Bali',
  CGK: 'Jakarta', SIN: 'Singapur', KUL: 'Kuala Lumpur', PEN: 'Penang', LGK: 'Langkawi', HAN: 'Hanoj',
  SGN: 'Ho Či Minovo Město', DAD: 'Da Nang', CXR: 'Nha Trang', PQC: 'Phu Quoc', REP: 'Siem Reap', PNH: 'Phnompenh',
  MNL: 'Manila', CEB: 'Cebu', HKG: 'Hongkong', MFM: 'Macao', TPE: 'Tchaj-pej', NRT: 'Tokio-Narita',
  HND: 'Tokio-Haneda', KIX: 'Ósaka', ICN: 'Soul', PEK: 'Peking', PKX: 'Peking-Daxing', PVG: 'Šanghaj',
  DEL: 'Dillí', BOM: 'Bombaj', GOI: 'Goa', GOX: 'Goa', CMB: 'Kolombo', MLE: 'Maledivy',
  KTM: 'Káthmándú', TAS: 'Taškent', SKD: 'Samarkand', ALA: 'Almaty', TBS: 'Tbilisi', KUT: 'Kutaisi',
  BUS: 'Batumi', EVN: 'Jerevan', GYD: 'Baku', JFK: 'New York', EWR: 'New York-Newark', LGA: 'New York-LaGuardia',
  MIA: 'Miami', FLL: 'Fort Lauderdale', MCO: 'Orlando', LAX: 'Los Angeles', SFO: 'San Francisco', LAS: 'Las Vegas',
  ORD: 'Chicago', BOS: 'Boston', IAD: 'Washington', YYZ: 'Toronto', YUL: 'Montréal', YVR: 'Vancouver',
  MEX: 'Ciudad de México', CUN: 'Cancún', HAV: 'Havana', VRA: 'Varadero', PUJ: 'Punta Cana', SDQ: 'Santo Domingo',
  MBJ: 'Jamajka (Montego Bay)', GIG: 'Rio de Janeiro', GRU: 'São Paulo', EZE: 'Buenos Aires', LIM: 'Lima', BOG: 'Bogotá',
  SCL: 'Santiago de Chile', PTY: 'Panama', SJO: 'Kostarika (San José)', UIO: 'Quito', SYD: 'Sydney', MEL: 'Melbourne',
  BNE: 'Brisbane', PER: 'Perth', AKL: 'Auckland', NAN: 'Fidži', PPT: 'Tahiti',
};

// Metropolitní oblasti s více letišti. lat/lon = centrum města (pro výpočet vzdálenosti).
export const METROS = [
  { code: 'LON', cs: 'Londýn', en: 'London', cc: 'GB', lat: 51.5074, lon: -0.1278, airports: ['LHR', 'LGW', 'STN', 'LTN', 'LCY', 'SEN'] },
  { code: 'PAR', cs: 'Paříž', en: 'Paris', cc: 'FR', lat: 48.8566, lon: 2.3522, airports: ['CDG', 'ORY', 'BVA'] },
  { code: 'MIL', cs: 'Milán', en: 'Milan', cc: 'IT', lat: 45.4642, lon: 9.19, airports: ['MXP', 'LIN', 'BGY'] },
  { code: 'ROM', cs: 'Řím', en: 'Rome', cc: 'IT', lat: 41.9028, lon: 12.4964, airports: ['FCO', 'CIA'] },
  { code: 'VCE', cs: 'Benátky', en: 'Venice', cc: 'IT', lat: 45.4408, lon: 12.3155, airports: ['VCE', 'TSF'] },
  { code: 'BRU', cs: 'Brusel', en: 'Brussels', cc: 'BE', lat: 50.8503, lon: 4.3517, airports: ['BRU', 'CRL'] },
  { code: 'STO', cs: 'Stockholm', en: 'Stockholm', cc: 'SE', lat: 59.3293, lon: 18.0686, airports: ['ARN', 'BMA', 'NYO', 'VST'] },
  { code: 'OSL', cs: 'Oslo', en: 'Oslo', cc: 'NO', lat: 59.9139, lon: 10.7522, airports: ['OSL', 'TRF'] },
  { code: 'WAW', cs: 'Varšava', en: 'Warsaw', cc: 'PL', lat: 52.2297, lon: 21.0122, airports: ['WAW', 'WMI'] },
  { code: 'BCN', cs: 'Barcelona', en: 'Barcelona', cc: 'ES', lat: 41.3874, lon: 2.1686, airports: ['BCN', 'GRO', 'REU'] },
  { code: 'FRA', cs: 'Frankfurt', en: 'Frankfurt', cc: 'DE', lat: 50.1109, lon: 8.6821, airports: ['FRA', 'HHN'] },
  { code: 'IST', cs: 'Istanbul', en: 'Istanbul', cc: 'TR', lat: 41.0082, lon: 28.9784, airports: ['IST', 'SAW'] },
  { code: 'MOW', cs: 'Moskva', en: 'Moscow', cc: 'RU', lat: 55.7558, lon: 37.6173, airports: ['SVO', 'DME', 'VKO'] },
  { code: 'TYO', cs: 'Tokio', en: 'Tokyo', cc: 'JP', lat: 35.6762, lon: 139.6503, airports: ['HND', 'NRT'] },
  { code: 'NYC', cs: 'New York', en: 'New York', cc: 'US', lat: 40.7128, lon: -74.006, airports: ['JFK', 'EWR', 'LGA'] },
  { code: 'WAS', cs: 'Washington', en: 'Washington', cc: 'US', lat: 38.9072, lon: -77.0369, airports: ['IAD', 'DCA', 'BWI'] },
  { code: 'CHI', cs: 'Chicago', en: 'Chicago', cc: 'US', lat: 41.8781, lon: -87.6298, airports: ['ORD', 'MDW'] },
  { code: 'BUH', cs: 'Bukurešť', en: 'Bucharest', cc: 'RO', lat: 44.4268, lon: 26.1025, airports: ['OTP', 'BBU'] },
  { code: 'BKK', cs: 'Bangkok', en: 'Bangkok', cc: 'TH', lat: 13.7563, lon: 100.5018, airports: ['BKK', 'DMK'] },
  { code: 'SEL', cs: 'Soul', en: 'Seoul', cc: 'KR', lat: 37.5665, lon: 126.978, airports: ['ICN', 'GMP'] },
  { code: 'DXB', cs: 'Dubaj', en: 'Dubai', cc: 'AE', lat: 25.2048, lon: 55.2708, airports: ['DXB', 'DWC'] },
  { code: 'TLV', cs: 'Tel Aviv', en: 'Tel Aviv', cc: 'IL', lat: 32.0853, lon: 34.7818, airports: ['TLV'] },
];

// Turistické regiony a ostrovy jako cíl („Kanáry“, „Kréta“ …).
export const REGIONS = [
  { key: 'kanary', cs: 'Kanárské ostrovy', aliases: ['kanary', 'kanarske ostrovy', 'canary islands', 'canaries'], airports: ['TFS', 'TFN', 'LPA', 'ACE', 'FUE', 'SPC'] },
  { key: 'baleary', cs: 'Baleáry', aliases: ['baleary', 'balearske ostrovy', 'balearic islands'], airports: ['PMI', 'IBZ', 'MAH'] },
  { key: 'mallorca', cs: 'Mallorca', aliases: ['mallorca', 'malorka', 'majorca'], airports: ['PMI'] },
  { key: 'kreta', cs: 'Kréta', aliases: ['kreta', 'crete'], airports: ['HER', 'CHQ'] },
  { key: 'sicilie', cs: 'Sicílie', aliases: ['sicilie', 'sicily', 'sicilia'], airports: ['PMO', 'CTA', 'TPS', 'CIY'] },
  { key: 'sardinie', cs: 'Sardinie', aliases: ['sardinie', 'sardinia', 'sardegna'], airports: ['CAG', 'OLB', 'AHO'] },
  { key: 'madeira', cs: 'Madeira', aliases: ['madeira'], airports: ['FNC'] },
  { key: 'azory', cs: 'Azory', aliases: ['azory', 'azores', 'acores'], airports: ['PDL', 'TER', 'HOR'] },
  { key: 'kypr', cs: 'Kypr', aliases: ['kypr', 'cyprus'], airports: ['LCA', 'PFO'] },
  { key: 'rhodos', cs: 'Rhodos', aliases: ['rhodos', 'rodos', 'rhodes'], airports: ['RHO'] },
  { key: 'korfu', cs: 'Korfu', aliases: ['korfu', 'corfu', 'kerkyra'], airports: ['CFU'] },
  { key: 'zakynthos', cs: 'Zakynthos', aliases: ['zakynthos', 'zante'], airports: ['ZTH'] },
  { key: 'santorini', cs: 'Santorini', aliases: ['santorini', 'thira'], airports: ['JTR'] },
  { key: 'kos', cs: 'Kos', aliases: ['kos'], airports: ['KGS'] },
  { key: 'chorvatske-pobrezi', cs: 'Chorvatské pobřeží', aliases: ['chorvatske pobrezi', 'jadran', 'dalmacie'], airports: ['SPU', 'DBV', 'ZAD', 'PUY', 'RJK'] },
  { key: 'algarve', cs: 'Algarve', aliases: ['algarve'], airports: ['FAO'] },
  { key: 'costa-del-sol', cs: 'Costa del Sol', aliases: ['costa del sol'], airports: ['AGP'] },
  { key: 'bali', cs: 'Bali', aliases: ['bali'], airports: ['DPS'] },
  { key: 'zanzibar', cs: 'Zanzibar', aliases: ['zanzibar'], airports: ['ZNZ'] },
  { key: 'maledivy', cs: 'Maledivy', aliases: ['maledivy', 'maldives'], airports: ['MLE'] },
  { key: 'mauricius', cs: 'Mauricius', aliases: ['mauricius', 'mauritius'], airports: ['MRU'] },
  { key: 'seychely', cs: 'Seychely', aliases: ['seychely', 'seychelles'], airports: ['SEZ'] },
  { key: 'phuket', cs: 'Phuket', aliases: ['phuket'], airports: ['HKT'] },
  { key: 'egypt-more', cs: 'Rudé moře (Egypt)', aliases: ['rude more', 'hurghada', 'sharm', 'egypt more'], airports: ['HRG', 'SSH', 'RMF'] },
  { key: 'turecka-riviera', cs: 'Turecká riviéra', aliases: ['turecka riviera', 'turecko more'], airports: ['AYT', 'DLM', 'BJV', 'GZP'] },
  { key: 'island', cs: 'Island', aliases: ['island', 'iceland'], airports: ['KEF'] },
];

// Další aliasy zemí (doplňují české názvy z data/countries.json).
export const COUNTRY_ALIASES = {
  cesko: 'CZ', 'ceska republika': 'CZ', cr: 'CZ', cechy: 'CZ', morava: 'CZ', czechia: 'CZ',
  slovensko: 'SK', rakousko: 'AT', nemecko: 'DE', polsko: 'PL', madarsko: 'HU',
  anglie: 'GB', britanie: 'GB', 'velka britanie': 'GB', uk: 'GB', skotsko: 'GB',
  usa: 'US', amerika: 'US', 'spojene staty': 'US', holandsko: 'NL', nizozemsko: 'NL',
  'emiraty': 'AE', 'spojene arabske emiraty': 'AE', 'jizni korea': 'KR', korea: 'KR',
};

export function cityCs(enCity) {
  return CITY_CS[enCity] || enCity;
}
